[name]
name = "8100_MAX"
version = "3.0"
author = "ShenEternity"

[[policy]]
from = 0
to = 3

[[policy]]
from = 4
to = 6

[[policy]]
from = 7
to = 7

[mode]
[mode.power]
idle_governor = "menu"
[[mode.power.policy]]
delay = 600
max_freq = 2000000
min_freq = 500000
can_boost_freq = 1000000
boost_freq = 2000000
margin = 2.1
diff = 70000
governor = "sugov_ext"
sleep_freq = 1000000

[[mode.power.policy]]
delay = 600
max_freq = 2250000
min_freq = 500000
can_boost_freq = 1000000
boost_freq = 2000000
margin = 2.2
diff = 70000
governor = "sugov_ext"
sleep_freq = 1000000


[[mode.power.policy]]
delay = 600
max_freq = 200000
min_freq = 500000
can_boost_freq = 1000000
boost_freq = 2000000
margin = 2.0
diff = 70000
governor = "sugov_ext"
sleep_freq = 1000000



[mode.blan]
idle_governor = "menu"
[[mode.blan.policy]]
delay = 400
max_freq = 2000000
min_freq = 500000
can_boost_freq = 1000000
boost_freq = 2000000
margin = 2.3
diff = 70000
governor = "sugov_ext"
sleep_freq = 1000000

[[mode.blan.policy]]
delay = 400
max_freq = 2650000
min_freq = 500000
can_boost_freq = 1000000
boost_freq = 2000000
margin = 2.3
diff = 70000
governor = "sugov_ext"
sleep_freq = 1000000

[[mode.blan.policy]]
delay = 400
max_freq = 2650000
min_freq = 500000
can_boost_freq = 1000000
boost_freq = 2000000
margin = 2.0
diff = 70000
governor = "sugov_ext"
sleep_freq = 1000000


[mode.perf]
idle_governor = "menu"
[[mode.perf.policy]]
delay = 200
max_freq = 2000000
min_freq = 500000
can_boost_freq = 1000000
boost_freq = 2000000
margin = 2.8
diff = 70000
governor = "sugov_ext"
sleep_freq = 1000000

[[mode.perf.policy]]
delay = 200
max_freq = 2850000
min_freq = 500000
can_boost_freq = 1000000
boost_freq = 2000000
margin = 2.8
diff = 70000
governor = "sugov_ext"
sleep_freq = 1000000

[[mode.perf.policy]]
delay = 200
max_freq = 2850000
min_freq = 500000
can_boost_freq = 1000000
boost_freq = 2000000
margin = 2.8
diff = 70000
governor = "sugov_ext"
sleep_freq = 1000000



[mode.fast]
idle_governor = "menu"
[[mode.fast.policy]]
delay = 100
max_freq = 2000000
min_freq = 500000
can_boost_freq = 1000000
boost_freq = 2000000
margin = 3.0
diff = 70000
governor = "sugov_ext"
sleep_freq = 1000000

[[mode.fast.policy]]
delay = 100
max_freq = 2850000
min_freq = 500000
can_boost_freq = 1000000
boost_freq = 2000000
margin = 3.0
diff = 70000
governor = "sugov_ext"
sleep_freq = 1000000

[[mode.fast.policy]]
delay = 100
max_freq = 2850000
min_freq = 500000
can_boost_freq = 1000000
boost_freq = 2000000
margin = 3.0
diff = 70000
governor = "sugov_ext"
sleep_freq = 1000000

